services:
  catalog-postgres:
    image: postgres:16
    networks:
      - commercecore
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalog_service
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  catalog-service:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - commercecore
    depends_on:
      catalog-postgres:
        condition: service_healthy
    ports:
      - "8086:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__CatalogDatabase: "Host=catalog-postgres;Port=5432;Database=catalog_service;Username=postgres;Password=postgres"
      Kafka__BootstrapServers: "kafka:29092"
      Kafka__SchemaRegistryUrl: "http://schema-registry:8081"
      Jwt__Key: "Kdr6AN7udG2fwt8TzqU7/lE37acTGV6PPlagtn5GusM="
      Jwt__Issuer: "CommerceCore.AuthenticationService"
      Jwt__Audience: "CommerceCore"
      Minio__Endpoint: "minio:9000"
      Minio__PublicBaseUrl: "localhost:9000"
      Minio__AccessKey: "minioadmin"
      Minio__SecretKey: "minioadmin"
      Minio__BucketName: "catalog-product-images"
      Minio__UseSSL: "false"
      Redis__ConnectionString: "redis:6379"
      Otel__TracesEndpoint: "http://jaeger:4317"
      Otel__LogsEndpoint: "http://otel-collector:4317"

networks:
  commercecore:
    external: true
    name: commercecore

volumes:
  postgres-data:
